development:
  bucket_name: appname_development
  access_key_id: 
  secret_access_key: 

test:
  bucket_name: appname_test
  access_key_id: 
  secret_access_key: 

production:
  bucket_name: roro-faces
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
